# Generated by Django 3.0.4 on 2020-03-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(max_length=1000)),
                ('comments', models.URLField()),
                ('pubDate', models.DateTimeField()),
            ],
        ),
    ]
