# Generated by Django 3.0.4 on 2020-03-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds_reader_app', '0002_auto_20200329_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='languages',
            new_name='language',
        ),
    ]
